### ISSUE TITLE
Web Example?

### ISSUE THREAD

**Issue by BrewDawg** [stevenh77/ClaimsBasedSecurityDemo#1]
I have everything working per your article on this. However, my Thread.CurrentPrincipal that I create after the cookie is created is literally blown away on the next web request. You really should create a bare bones MVC 5 app that shows how to use this? A one time claim created and accessed in a console app is far different than having that claiming stick around between web requests?  Your example was extremely helpful, it just falls short of using it in the real world, ie, how does a claim related to a cookie? or does it? and how does your claim get reconstituted between web requests?

**Comment by stevenh77** [comment]
Thanks Mike.  Don't forget a browser is just one use case scenario for accessing secure resources.

The code was written as a simple example to show how the role based security works.
